// Code generated by MockGen. DO NOT EDIT.
// Source: category_service.go

// Package test is a generated GoMock package.
package mock

import (
	model "echo-rest-api/model"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockCategoryService is a mock of CategoryService interface
type MockCategoryService struct {
	ctrl     *gomock.Controller
	recorder *MockCategoryServiceMockRecorder
}

// MockCategoryServiceMockRecorder is the mock recorder for MockCategoryService
type MockCategoryServiceMockRecorder struct {
	mock *MockCategoryService
}

// NewMockCategoryService creates a new mock instance
func NewMockCategoryService(ctrl *gomock.Controller) *MockCategoryService {
	mock := &MockCategoryService{ctrl: ctrl}
	mock.recorder = &MockCategoryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCategoryService) EXPECT() *MockCategoryServiceMockRecorder {
	return m.recorder
}

// GetCategory mocks base method
func (m *MockCategoryService) GetCategory(id int) (*model.Category, error) {
	ret := m.ctrl.Call(m, "GetCategory", id)
	ret0, _ := ret[0].(*model.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategory indicates an expected call of GetCategory
func (mr *MockCategoryServiceMockRecorder) GetCategory(id interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategory", reflect.TypeOf((*MockCategoryService)(nil).GetCategory), id)
}

// GetCategories mocks base method
func (m *MockCategoryService) GetCategories() ([]*model.Category, error) {
	ret := m.ctrl.Call(m, "GetCategories")
	ret0, _ := ret[0].([]*model.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategories indicates an expected call of GetCategories
func (mr *MockCategoryServiceMockRecorder) GetCategories() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategories", reflect.TypeOf((*MockCategoryService)(nil).GetCategories))
}

// CreateCategory mocks base method
func (m *MockCategoryService) CreateCategory(category *model.Category) (*int, error) {
	ret := m.ctrl.Call(m, "CreateCategory", category)
	ret0, _ := ret[0].(*int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCategory indicates an expected call of CreateCategory
func (mr *MockCategoryServiceMockRecorder) CreateCategory(category interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategory", reflect.TypeOf((*MockCategoryService)(nil).CreateCategory), category)
}

// UpdateCategory mocks base method
func (m *MockCategoryService) UpdateCategory(category *model.Category) error {
	ret := m.ctrl.Call(m, "UpdateCategory", category)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCategory indicates an expected call of UpdateCategory
func (mr *MockCategoryServiceMockRecorder) UpdateCategory(category interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCategory", reflect.TypeOf((*MockCategoryService)(nil).UpdateCategory), category)
}

// DeleteCategory mocks base method
func (m *MockCategoryService) DeleteCategory(id int) error {
	ret := m.ctrl.Call(m, "DeleteCategory", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCategory indicates an expected call of DeleteCategory
func (mr *MockCategoryServiceMockRecorder) DeleteCategory(id interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCategory", reflect.TypeOf((*MockCategoryService)(nil).DeleteCategory), id)
}
