// Code generated by MockGen. DO NOT EDIT.
// Source: store.go

// Package test is a generated GoMock package.
package mock

import (
	sql "database/sql"
	model "echo-rest-api/model"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockStore is a mock of Store interface
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Close mocks base method
func (m *MockStore) Close() error {
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockStoreMockRecorder) Close() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockStore)(nil).Close))
}

// Begin mocks base method
func (m *MockStore) Begin() (*sql.Tx, error) {
	ret := m.ctrl.Call(m, "Begin")
	ret0, _ := ret[0].(*sql.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin
func (mr *MockStoreMockRecorder) Begin() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockStore)(nil).Begin))
}

// Commit mocks base method
func (m *MockStore) Commit(tx *sql.Tx) error {
	ret := m.ctrl.Call(m, "Commit", tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit
func (mr *MockStoreMockRecorder) Commit(tx interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockStore)(nil).Commit), tx)
}

// Rollback mocks base method
func (m *MockStore) Rollback(tx *sql.Tx) error {
	ret := m.ctrl.Call(m, "Rollback", tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback
func (mr *MockStoreMockRecorder) Rollback(tx interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockStore)(nil).Rollback), tx)
}

// GetCategory mocks base method
func (m *MockStore) GetCategory(tx *sql.Tx, id int) (*model.Category, error) {
	ret := m.ctrl.Call(m, "GetCategory", tx, id)
	ret0, _ := ret[0].(*model.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategory indicates an expected call of GetCategory
func (mr *MockStoreMockRecorder) GetCategory(tx, id interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategory", reflect.TypeOf((*MockStore)(nil).GetCategory), tx, id)
}

// GetCategories mocks base method
func (m *MockStore) GetCategories(tx *sql.Tx) ([]*model.Category, error) {
	ret := m.ctrl.Call(m, "GetCategories", tx)
	ret0, _ := ret[0].([]*model.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategories indicates an expected call of GetCategories
func (mr *MockStoreMockRecorder) GetCategories(tx interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategories", reflect.TypeOf((*MockStore)(nil).GetCategories), tx)
}

// CreateCategory mocks base method
func (m *MockStore) CreateCategory(tx *sql.Tx, category *model.Category) (*int, error) {
	ret := m.ctrl.Call(m, "CreateCategory", tx, category)
	ret0, _ := ret[0].(*int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCategory indicates an expected call of CreateCategory
func (mr *MockStoreMockRecorder) CreateCategory(tx, category interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategory", reflect.TypeOf((*MockStore)(nil).CreateCategory), tx, category)
}

// UpdateCategory mocks base method
func (m *MockStore) UpdateCategory(tx *sql.Tx, category *model.Category) error {
	ret := m.ctrl.Call(m, "UpdateCategory", tx, category)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCategory indicates an expected call of UpdateCategory
func (mr *MockStoreMockRecorder) UpdateCategory(tx, category interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCategory", reflect.TypeOf((*MockStore)(nil).UpdateCategory), tx, category)
}

// DeleteCategory mocks base method
func (m *MockStore) DeleteCategory(tx *sql.Tx, id int) error {
	ret := m.ctrl.Call(m, "DeleteCategory", tx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCategory indicates an expected call of DeleteCategory
func (mr *MockStoreMockRecorder) DeleteCategory(tx, id interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCategory", reflect.TypeOf((*MockStore)(nil).DeleteCategory), tx, id)
}

// GetProduct mocks base method
func (m *MockStore) GetProduct(tx *sql.Tx, id int) (*model.Product, error) {
	ret := m.ctrl.Call(m, "GetProduct", tx, id)
	ret0, _ := ret[0].(*model.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProduct indicates an expected call of GetProduct
func (mr *MockStoreMockRecorder) GetProduct(tx, id interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProduct", reflect.TypeOf((*MockStore)(nil).GetProduct), tx, id)
}

// GetProducts mocks base method
func (m *MockStore) GetProducts(tx *sql.Tx, category *int) ([]*model.Product, error) {
	ret := m.ctrl.Call(m, "GetProducts", tx, category)
	ret0, _ := ret[0].([]*model.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProducts indicates an expected call of GetProducts
func (mr *MockStoreMockRecorder) GetProducts(tx, category interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProducts", reflect.TypeOf((*MockStore)(nil).GetProducts), tx, category)
}

// CreateProduct mocks base method
func (m *MockStore) CreateProduct(tx *sql.Tx, product *model.Product) (*int, error) {
	ret := m.ctrl.Call(m, "CreateProduct", tx, product)
	ret0, _ := ret[0].(*int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProduct indicates an expected call of CreateProduct
func (mr *MockStoreMockRecorder) CreateProduct(tx, product interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockStore)(nil).CreateProduct), tx, product)
}

// UpdateProduct mocks base method
func (m *MockStore) UpdateProduct(tx *sql.Tx, product *model.Product) error {
	ret := m.ctrl.Call(m, "UpdateProduct", tx, product)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProduct indicates an expected call of UpdateProduct
func (mr *MockStoreMockRecorder) UpdateProduct(tx, product interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockStore)(nil).UpdateProduct), tx, product)
}

// DeleteProduct mocks base method
func (m *MockStore) DeleteProduct(tx *sql.Tx, id int) error {
	ret := m.ctrl.Call(m, "DeleteProduct", tx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProduct indicates an expected call of DeleteProduct
func (mr *MockStoreMockRecorder) DeleteProduct(tx, id interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockStore)(nil).DeleteProduct), tx, id)
}
